# Generated by Django 5.0.3 on 2024-03-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
